#!/usr/bin/python

from flask import Flask, jsonify
from rest import categories, items, auth
from client import sample

app = Flask(__name__)

app.register_blueprint(auth.auth_rest)
app.register_blueprint(categories.categories_rest)
app.register_blueprint(items.items_rest)
app.register_blueprint(sample.client_rest)

@app.after_request
def after_request(response):
	response.headers.add('Access-Control-Allow-Origin', '*')
	response.headers.add('Access-Control-Allow-Headers', 'Content-Type,Authorization')
	response.headers.add('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS')
	return response

if __name__ == '__main__':
	app.run(debug=True, host='0.0.0.0', port=8080)
